name: Cliente Gestión Notificaciones

on:
  push:
    branches:
      - main
    paths:
      - 'clientes/*.txt'  # Vigilar archivos en la carpeta de clientes
  issues:
    types: [opened, edited]  # Vigilar cuando se abran o editen "Issues"

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Notificar cambios
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            if [[ "${{ github.event.commits[0].added }}" != "" ]]; then
              echo "Un nuevo cliente ha sido creado en el sistema."
            elif [[ "${{ github.event.commits[0].modified }}" != "" ]]; then
              echo "Los datos de un cliente existente han sido modificados."
            elif [[ "${{ github.event.commits[0].removed }}" != "" ]]; then
              echo "Consulta realizada sobre la información de un cliente."
            fi
          elif [[ "${{ github.event_name }}" == "issues" ]]; then
            if [[ "${{ github.event.action }}" == "opened" || "${{ github.event.action }}" == "edited" ]]; then
              labels=$(echo "${{ github.event.issue.labels[*].name }}")
              if [[ "$labels" == *"enhancement"* ]]; then
                echo "Se ha solicitado una mejora a la aplicación."
              elif [[ "$labels" == *"feature-request"* ]]; then
                echo "Se ha solicitado una nueva función para la aplicación."
              fi
            fi
          fi
